spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mariadb://172.168.10.101:3306/microsvs
    username: golden
    password: golden
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
      show-sql: true
  config:
    import: optional:configserver:http://localhost:8085
  profiles:
    active:
      - default


server:
  port: 8081

#eureka:
 # instance:
  #  appname: user-service
  #  prefer-ip-address : true
  #client:
   # register-with-eureka: true
   # fetch-registry: true
  #serviceUrl:
   # defaultZone: http://localhost:8761
